name: result_x
description: A lightweight, idiomatic Dart result type. Built on Dart 3 with zero dependencies. Features Trace<T,E>, Ok, Err, split, map, mapError and bind.
version: 1.0.0
repository: https://github.com/seyifunmi92/ResultX-Plugin

environment:
  sdk: ^3.11.1

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
